# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  name: "build_to_nuget_pakcages"
  inputs:
    filePath: './nupkg/pack.ps1'
    pwsh: true
    workingDirectory: './nupkg'

- task: PowerShell@2
  name: "publish_to_nuget"
  inputs:
    filePath: './nupkg/push_packages.ps1'
    arguments: $(nuget_key)
    pwsh: true
    workingDirectory: './nupkg'
